import Head from 'next/head'

const Home = () => {
  return (
    <div>
      <Head>
        <title>Consortio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/logo.svg" />
      </Head>
    </div>
  )
}

export default Home
